In [1]:
!pip install ktrain
!pip install tensorflow_text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 25.3 MB 1.6 MB/s 
     |████████████████████████████████| 981 kB 42.9 MB/s 
     |████████████████████████████████| 263 kB 44.6 MB/s 
     |████████████████████████████████| 3.8 MB 42.0 MB/s 
     |████████████████████████████████| 1.3 MB 46.2 MB/s 
     |████████████████████████████████| 468 kB 50.9 MB/s 
     |████████████████████████████████| 6.6 MB 43.0 MB/s 
     |████████████████████████████████| 101 kB 11.9 MB/s 
     |████████████████████████████████| 880 kB 58.8 MB/s 
     |████████████████████████████████| 596 kB 40.2 MB/s 
  Created wheel for ktrain: filename=ktrain-0.31.7-py3-none-any.whl size=25312842 sha256=564c5823b1e6caca2c9bded8a988e737fd23902a965e445ea4fdb75055924815
  Stored in directory: /root/.cache/pip/wheels/e5/98/8e/ce355dcb92451e85fab93f7ea2da068843e93e703928cd06fb
  Created wheel for keras-bert: filename=keras_bert-0.89.0-p

In [9]:
import tensorflow_hub as hub
import tensorflow_text as text 

In [10]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [13]:
bert_preprocessing_model = hub.KerasLayer(preprocess_url)

In [16]:
bert_preprocessing_model

In [17]:
test_text = ['harsh is again doing something crazy' , 'python is awesome programming language']

In [30]:
text_preprocessing = bert_preprocessing_model(test_text)
text_preprocessing

{'input_word_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[  101,  8401,  2003,  2153,  2725,  2242,  4689,   102,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     

In [31]:
text_preprocessing.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [32]:
text_preprocessing['input_mask'] 

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [33]:
text_preprocessing['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [34]:
text_preprocessing['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  8401,  2003,  2153,  2725,  2242,  4689,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [29]:
bert_model = hub.KerasLayer(encoder_url)

In [35]:
bert_results = bert_model(text_preprocessing)
bert_results.keys()

dict_keys(['default', 'sequence_output', 'pooled_output', 'encoder_outputs'])

In [36]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.83410805, -0.2322368 ,  0.21249002, ...,  0.34023008,
        -0.5311639 ,  0.860995  ],
       [-0.940929  , -0.53784996, -0.73908263, ..., -0.7275779 ,
        -0.7033794 ,  0.92137676]], dtype=float32)>

In [39]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.14512955, -0.04663784, -0.06797672, ...,  0.01886639,
           0.02612185,  0.04844405],
         [ 0.31881052,  0.470336  , -0.6021704 , ..., -0.03581978,
           0.73991007, -0.32000577],
         [-0.38064557, -0.30606386, -0.49180156, ...,  0.06443559,
           0.96097636,  0.46114418],
         ...,
         [-0.1691106 , -0.21787702,  0.59607756, ...,  0.40967274,
          -0.23059924,  0.0363085 ],
         [-0.2387492 , -0.2386885 ,  0.45198804, ...,  0.42598152,
          -0.13638699, -0.03050389],
         [-0.1172392 , -0.17866592,  0.46423876, ...,  0.7007493 ,
          -0.42095307, -0.10305829]],
 
        [[ 0.2280519 , -0.07494813, -0.0573393 , ..., -0.04327833,
           0.09086621, -0.02263676],
         [ 0.7923454 ,  0.28817326, -0.12036911, ..., -1.434241  ,
           0.5563331 , -0.23250048],
         [-0.37119588,  0.03880043, -0.22485697, ..., -0.0950242 ,
           0.62057424,  0.44

In [38]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.08928319,  0.23662646,  0.06084459, ..., -0.22775653,
          0.15064862,  0.18412386],
        [-0.07529007,  0.23385845,  0.06623632, ..., -0.53830385,
          0.24845329, -0.30960697],
        [ 0.19369763, -0.15605225,  0.08951192, ..., -0.4226138 ,
          0.32980126,  0.32765725],
        ...,
        [-0.19041106,  0.07459819,  0.08717532, ..., -0.00827294,
          0.02151456, -0.17575894],
        [-0.1409568 ,  0.09397881,  0.12879409, ..., -0.01383958,
          0.02327409, -0.14852189],
        [-0.11868151,  0.12946516,  0.17325169, ..., -0.00611965,
          0.01608767, -0.14178678]],

       [[-0.30931208,  0.10855472, -0.18312459, ..., -0.65826726,
         -0.06414353,  0.7192082 ],
        [ 0.26263005,  0.4446319 , -0.2269212 , ..., -0.28770095,
          0.30560243, -0.0251141 ],
        [-0.03861475, -0.33137676,  0.22375868, ..., -0.5211163 ,
          0.32179275,  0.7325723 ],
        ...,